wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
    start_time: 1655658036
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 8
      4: 3.7.9
      5: 0.12.15
      8:
      - 5
